# Shared across ALL environments
spring.application.name=taskmanager
app.name=Task Manager
app.version=1.0.0

# Which profile is active?
# Change this to switch environments
spring.profiles.active=dev
